#!/bin/sh

# Print error info if $# != 1 or n isn't an integer
test $# -eq 1 && (echo "$1" | awk "
/^[0-9]+$/ {exit 0} 
/.*/ {exit 1}
")
if [ ! $? ]; then
	echo "Usage: archive <n>" 1>&2
	exit 1
fi

if [ "x$LRU_DIR" == "x" ]; then
	LRU_DIR="$HOME/projs"
fi

TAG="$1\. "
FNAME=`files | grep "$TAG" | sed 's/[0-9][0-9]*\. *//'`
NEWNAME=`echo "$FNAME" | sed 's/P1/P2/'`

mv "$LRU_DIR/$FNAME" "$LRU_DIR/$NEWNAME"
