#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: folder <subject>" 1>&2
	exit 1
fi

if [ "x$LRU_DIR" == "x" ]; then
	LRU_DIR="$HOME/projs"
fi

TOPIC="$1"
SUBJECTS=`ls -F "$LRU_DIR" | grep "^[0-9]\{8\}-P[12]-" | sed 's/^[0-9]\{8\}-P[12]-//'`

echo "$SUBJECTS" | grep "^$TOPIC/$" 1>/dev/null
if [ $? -eq 0 ]; then
	echo "A folder with that name already exists (don't forget the archives)." 1>&2
	exit 1
fi

NAME="`date +%Y%m%d`-P1-$TOPIC"
mkdir "$LRU_DIR/$NAME"
