#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: pull <n>" 1>&2
	exit 1
fi

FOLDERS=`files`
TAG="$1\. "

FOLDER=`echo "$FOLDERS" | grep "^$TAG" | sed "s/^$TAG//"`
FNAME=`basename "$FOLDER"`

# Update the LRU stamp
touch "$FOLDER"

# Make sure the mount point exists
mkdir -p "$FNAME"
bindfs -n "$FOLDER" "$FNAME" 
